#!/usr/bin/env python3
"""Build the samples corpus fixture (samples-az-corpus.json) for policy.corpus.test.ts.

The corpus is every `az` command in the localstack-azure-samples repo, at the pinned commit,
with the argv the Azure client's tokenizer must produce. Each distinct command is one case with:

  * `command`   - the arguments a model would send, without the leading `az` (expansions replaced
                  by placeholder words: $VAR -> x_var, $(...) -> x_subst, ...);
  * `argv`      - the expected argv, generated by GNU bash's `printf '%s\0'`;
  * `origins`   - the `file:line` locations the command appears at (deduplicated);
  * `expect`    - "ok", or {"ruleId": ...} for the seven sample steps the policy refuses.

Inputs: extract.py's extracted.json and bash_argv.py's bash.json, both in CORPUS_WORK_DIR
(default: next to this file). README.md has the whole run.
"""
import argparse
import datetime
import json
import os
import pathlib

HERE = pathlib.Path(__file__).parent
WORK = pathlib.Path(os.environ.get("CORPUS_WORK_DIR", str(HERE)))
OUT = HERE / "samples-az-corpus.json"

# The seven sample steps the policy refuses. Keyed by the exact command string; the value is the
# policy rule id the test asserts. These are the only non-"ok" verdicts in the corpus; if the
# policy ever refuses another case, the test fails loudly.
KNOWN_REFUSALS = {
    'acr login --name "x_acr_name" --only-show-errors': "denied:acr-login",
    (
        'container exec --name "x_aci_group_name" --resource-group "x_resource_group_name" '
        '--container-name "x_aci_group_name" --exec-command "echo hello-from-exec"'
    ): "denied:container-exec",
}


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--work-dir",
        default=str(WORK),
        help="where extracted.json and bash.json are (default: CORPUS_WORK_DIR, else this directory)",
    )
    parser.add_argument("--out", default=str(OUT), help="the fixture to write (default: %(default)s)")
    args = parser.parse_args()

    work = pathlib.Path(args.work_dir)
    extracted = json.loads((work / "extracted.json").read_text(encoding="utf-8"))
    bash = json.loads((work / "bash.json").read_text(encoding="utf-8"))

    records = []
    for index, command in enumerate(extracted["commands"]):
        origin = f'{command["file"]}:{command["line"]}'
        argv = bash["argv"].get(str(index))
        if argv is None:
            reason = bash.get("refused", {}).get(str(index), "no argv")
            raise SystemExit(f"bash_argv.py gave no argv for {origin}: {reason}")
        records.append((command["command"], argv, origin))

    by_command: dict[str, dict] = {}
    for command, argv, origin in records:
        entry = by_command.setdefault(command, {"command": command, "argv": argv, "origins": set()})
        if entry["argv"] != argv:
            raise SystemExit(f"argv disagreement across duplicates of: {command!r}")
        entry["origins"].add(origin)

    cases = []
    refusal_count = 0
    for command in sorted(by_command):
        entry = by_command[command]
        expect: object = "ok"
        if command in KNOWN_REFUSALS:
            expect = {"ruleId": KNOWN_REFUSALS[command]}
            refusal_count += len(entry["origins"])
        cases.append(
            {
                "command": command,
                "argv": entry["argv"],
                "origins": sorted(entry["origins"]),
                "expect": expect,
            }
        )

    if len(cases) != 736:
        raise SystemExit(f"expected 736 distinct cases, got {len(cases)}")
    if refusal_count != 7:
        raise SystemExit(f"expected 7 refused script occurrences, got {refusal_count}")

    document = {
        "_metadata": {
            "description": (
                "Every az command in localstack-azure-samples, deduplicated, with the expected "
                "argv and policy verdict. Consumed by src/lib/azure/policy.corpus.test.ts."
            ),
            "source_repo": "localstack-azure-samples (samples/**/*.sh)",
            "source_commit": extracted["source_commit"],
            "built_from": "extract.py and bash_argv.py (see README.md)",
            "generated_utc": datetime.datetime.now(datetime.timezone.utc)
            .isoformat(timespec="seconds")
            .replace("+00:00", "Z"),
            "command_count": len(records),
            "distinct_count": len(cases),
            "refused_occurrences": refusal_count,
            "known_refusals": [
                {"command": command, "ruleId": rule_id} for command, rule_id in KNOWN_REFUSALS.items()
            ],
            "note": (
                "Regenerate on a samples bump: see README.md. argv is bash `printf` output. "
                "Placeholder values (x_var) stand in for shell expansions, so the fixture exercises "
                "quoting exactly as the scripts write it."
            ),
        },
        "cases": cases,
    }
    out = pathlib.Path(args.out)
    # LF on every platform (Python would write CRLF on Windows).
    out.write_text(
        json.dumps(document, indent=1, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n"
    )
    print(f"wrote {out} ({len(cases)} cases, {refusal_count} refused occurrences)")


if __name__ == "__main__":
    main()
