#!/usr/bin/env python3
"""Build the U2 corpus fixture (samples-az-corpus.json) for policy.corpus.test.ts.

The corpus is every `az` command in the localstack-azure-samples repo, at the pinned commit,
tokenized the way the Azure client tokenizes (variant P). Each distinct command is one case with:

  * `command`   - the arguments a model would send, without the leading `az` (expansions replaced
                  by placeholder words: $VAR -> x_var, $(...) -> x_subst, ...);
  * `argv`      - the expected argv, generated by GNU bash's `printf '%s\0'` and cross-checked
                  against Python's shlex (identical on every case; see C06);
  * `origins`   - the `file:line` locations the command appears at (deduplicated);
  * `expect`    - "ok", or {"ruleId": ...} for the seven sample steps the policy refuses (N1).

How this file was built
-----------------------
It is assembled from the C06 artifact `samples-az-corpus.json`, which check C06 produced at commit
4193d67 by running `extract.py` (the bash-lexer extractor, shipped next to this script) and
`bash_argv.py` (the bash `printf` oracle, also shipped here). The artifact's `cases[].argv` and
`disagreements[].shlex_argv` are the bash-verified argv for all 1,985 commands.

To regenerate from scratch on a samples bump (decision DR8), see README.md: run extract.py against
the new checkout, run bash_argv.py, then run this script pointed at the fresh artifact with
--from-artifact, or adapt it to read extracted.json + bash.json directly.
"""
import argparse
import datetime
import json
import pathlib

HERE = pathlib.Path(__file__).parent
OUT = HERE / "samples-az-corpus.json"

# The seven sample steps the C08 side-effect rules refuse (review R02 N1). Keyed by the exact
# command string; the value is the policy rule id the test asserts. These are the only non-"ok"
# verdicts in the corpus; if the policy ever refuses another case, the test fails loudly.
KNOWN_REFUSALS = {
    'acr login --name "x_acr_name" --only-show-errors': "denied:acr-login",
    (
        'container exec --name "x_aci_group_name" --resource-group "x_resource_group_name" '
        '--container-name "x_aci_group_name" --exec-command "echo hello-from-exec"'
    ): "denied:container-exec",
}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--from-artifact",
        required=True,
        help="the C06 artifact samples-az-corpus.json (see README.md for how to produce one)",
    )
    args = parser.parse_args()

    artifact = json.loads(pathlib.Path(args.from_artifact).read_text(encoding="utf-8"))

    records = []
    for case in artifact["cases"]:
        records.append((case["command"], case["argv"], f'{case["file"]}:{case["line"]}'))
    for dis in artifact["disagreements"]:
        # The 76 commands the AWS tokenizer rejected but variant P accepts; shlex_argv == bash argv.
        records.append((dis["command"], dis["shlex_argv"], f'{dis["file"]}:{dis["line"]}'))

    by_command: dict[str, dict] = {}
    for command, argv, origin in records:
        entry = by_command.setdefault(command, {"command": command, "argv": argv, "origins": set()})
        if entry["argv"] != argv:
            raise SystemExit(f"argv disagreement across duplicates of: {command!r}")
        entry["origins"].add(origin)

    cases = []
    refusal_count = 0
    for command in sorted(by_command):
        entry = by_command[command]
        expect: object = "ok"
        if command in KNOWN_REFUSALS:
            expect = {"ruleId": KNOWN_REFUSALS[command]}
            refusal_count += len(entry["origins"])
        cases.append(
            {
                "command": command,
                "argv": entry["argv"],
                "origins": sorted(entry["origins"]),
                "expect": expect,
            }
        )

    if len(cases) != 736:
        raise SystemExit(f"expected 736 distinct cases, got {len(cases)}")
    if refusal_count != 7:
        raise SystemExit(f"expected 7 refused script occurrences, got {refusal_count}")

    document = {
        "_metadata": {
            "description": (
                "Every az command in localstack-azure-samples, deduplicated, with the expected "
                "variant-P argv and policy verdict. Consumed by src/lib/azure/policy.corpus.test.ts."
            ),
            "source_repo": artifact["source_repo"],
            "source_commit": artifact["source_commit"],
            "built_from": "checks/artifacts/samples-az-corpus.json (check C06)",
            "generated_utc": datetime.datetime.now(datetime.timezone.utc)
            .isoformat(timespec="seconds")
            .replace("+00:00", "Z"),
            "command_count": len(records),
            "distinct_count": len(cases),
            "refused_occurrences": refusal_count,
            "known_refusals": [
                {"command": command, "ruleId": rule_id, "source": "review R02 N1"}
                for command, rule_id in KNOWN_REFUSALS.items()
            ],
            "note": (
                "Regenerate on a samples bump (DR8): see README.md. argv is bash `printf` output, "
                "identical to Python shlex on every case (C06). Placeholder values (x_var) stand in "
                "for shell expansions, so the fixture exercises quoting exactly as the scripts write it."
            ),
        },
        "cases": cases,
    }
    OUT.write_text(json.dumps(document, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(cases)} cases, {refusal_count} refused occurrences)")


if __name__ == "__main__":
    main()
